import { Metadata } from "next";
import { Mail, MapPin } from "lucide-react";
import FacebookIcon from "@/components/FacebookIcon";
import HeroSection from "@/components/HeroSection";
import ContactForm from "@/components/ContactForm";
import InnerCta from "@/components/InnerCta";
import styles from "@/components/InnerPage.module.css";
import { pageSeo } from "@/lib/seo";
export const metadata: Metadata = pageSeo({ title: "Contact LGBTQIA++ Ku-Ila", description: "Contact LGBTQIA++ SILBI Kumintang Ilaya in Batangas City for support, membership, events, and community questions.", path: "/contact", image: "/images/stock/stock-10.jpg" });
const contactInfo = [{ icon:MapPin, label:"Location", value:"Kumintang Ilaya, Batangas City, Philippines" }, { icon:Mail, label:"Email", value:"lgbtkuila@outlook.com", href:"mailto:lgbtkuila@outlook.com" }, { icon:FacebookIcon, label:"Facebook", value:"Ku-Ila LGBTQIA++", href:"https://www.facebook.com/profile.php?id=61591420257367" }];
export default function ContactPage(){return <main><HeroSection title="Contact Us" subtitle="Home / Contact Us" description="Questions, ideas, and new connections are always welcome here." backgroundImage="/images/stock/stock-10.jpg" />
  <section className={`${styles.section} ${styles.cream}`}><div className={styles.wrap}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Let&apos;s talk</p><h2 className={styles.heading}>A conversation can<br />be a <em>beginning.</em></h2></div><p className={styles.lead}>Send us a message and our team will respond as soon as we can.</p></div><div className={styles.formLayout}><div><ContactForm /></div><aside className={styles.aside}><p className={styles.eyebrow}>Reach out</p><h3>Find Ku-Ila</h3>{contactInfo.map(({icon:Icon,label,value,href})=>{const content=<><span className={styles.featureIcon}><Icon size={18}/></span><div><b>{label}</b><span>{value}</span></div></>;return href?<a key={label} className={`${styles.feature} transition hover:text-[#f15a24]`} href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noopener noreferrer":undefined}>{content}</a>:<div key={label} className={styles.feature}>{content}</div>})}</aside></div></div></section><InnerCta label="Our community" title={<>Kahit ano ka,<br /><em>Love ka!</em></>} description="The door is open for people looking for support, community, or a place to begin." primaryHref="/become-member" primaryLabel="Become a member" /></main>;}
