import type { Metadata } from "next";
import Image from "next/image";
import { Check } from "lucide-react";
import HeroSection from "@/components/HeroSection";
import MembershipForm from "@/components/MembershipForm";
import InnerCta from "@/components/InnerCta";
import styles from "@/components/InnerPage.module.css";
import { pageSeo, breadcrumbJsonLd } from "@/lib/seo";
export const metadata: Metadata = pageSeo({ title: "Become a Ku-Ila Member", description: "Join LGBTQIA++ SILBI Kumintang Ilaya for community programs, support, advocacy, and a place to belong.", path: "/become-member", image: "/images/stock/stock-04.jpg" });
const benefits = ["Official LGBTQIA++ SILBI Kumintang Ilaya member", "Access to community events and programs", "Legal assistance and advocacy support", "Health and wellness resources"];
const breadcrumb=breadcrumbJsonLd([{name:"Home",path:"/"},{name:"Become a Member",path:"/become-member"}]);
export default function BecomeMemberPage() { return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><HeroSection title="Become a Member" subtitle="Home / Become a Member" description="Belong to a community that makes room for your voice, your story, and your future." backgroundImage="/images/stock/stock-04.jpg" />
  <section className={styles.section}><div className={styles.wrap}><div className={styles.formLayout}><div><p className={styles.eyebrow}>Join Ku-Ila</p><h2 className={styles.heading}>Your place in the<br /><em>community.</em></h2><p className={styles.lead}>Complete the application below and we will guide you through the next steps.</p><div className="mt-10"><MembershipForm /></div></div><aside className={styles.aside}><p className={styles.eyebrow}>Membership details</p><h3>One small step<br />toward belonging.</h3><p className="mb-7 font-[family-name:var(--font-heading)] text-4xl text-[#f15a24]">₱300</p><p className="mb-5 text-sm leading-relaxed text-[#0a1d4a]/65">Scan to pay the one-time membership fee, then upload the payment screenshot and reference number in your application.</p><Image src="/images/instapay-qr.png" width={320} height={320} alt="InstaPay QR code for Ku-Ila membership payment" className="mb-8 w-full max-w-[320px] rounded-xl border border-[#0a1d4a]/10 bg-white p-2" /><ol className={styles.steps}>{["Fill out the membership form.", "Send ₱300 via InstaPay or GCash.", "Add the reference number and screenshot.", "Wait for confirmation from our team."].map((step,index)=><li key={step}><span>0{index+1}</span>{step}</li>)}</ol><div className={styles.notice}><b className="mb-3 block text-[#0a1d4a]">What membership opens up</b>{benefits.map(benefit=><div className="mb-3 flex gap-2 text-sm" key={benefit}><Check size={15} className="mt-1 shrink-0 text-[#f15a24]"/>{benefit}</div>)}</div></aside></div></div></section><InnerCta label="Need a hand?" title={<>We are here<br />to <em>help.</em></>} description="If you have questions about membership, our team will be glad to talk you through it." /></main>; }
