import { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, Pencil } from "lucide-react";
import FacebookIcon from "@/components/FacebookIcon";
import HeroSection from "@/components/HeroSection";
import InnerCta from "@/components/InnerCta";
import styles from "@/components/InnerPage.module.css";
import { members } from "@/lib/data";
export function generateStaticParams(){return members.map(member=>({slug:member.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const member=members.find(m=>m.slug===slug);return member?{title:member.name,description:`Learn more about ${member.name}, ${member.role} at LGBTQIA++ SILBI Kumintang Ilaya.`}:{title:"Member Not Found"};}
export default async function MemberPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const member=members.find(m=>m.slug===slug);if(!member)notFound();return <main><HeroSection title={member.name} subtitle={`Home / Members / ${member.name}`} description="A member of the community helping make room for more voices, more stories, and more belonging." backgroundImage="/images/stock/stock-09.jpg" />
  <section className={styles.section}><div className={styles.wrap}><div className={styles.detail}><div className={styles.portrait}><Image src={member.image} alt={member.name} fill sizes="(max-width:820px) 90vw, 40vw" /></div><div className={styles.copy}><p className={styles.eyebrow}>Member profile</p><h2 className={styles.heading}>{member.name}</h2><p className={styles.tag}>{member.role}</p><p>As a valued member of LGBTQIA++ SILBI Kumintang Ilaya, {member.name} takes part in the work of building a more caring, connected community.</p><div className={styles.featureList}>{["Community support and safe spaces", "Legal assistance and advocacy", "Youth empowerment programs", "Health and wellness initiatives"].map((item,index)=><div className={styles.feature} key={item}><span className={styles.featureIcon}>0{index+1}</span><div>{item}</div></div>)}</div><div className={styles.actions}>{member.facebookUrl?<a className={styles.primaryButton} href={member.facebookUrl} target="_blank" rel="noopener noreferrer"><FacebookIcon className="h-4 w-4"/> Facebook profile</a>:null}<Link href={`/contact?subject=Profile%20Update%20Request%20-%20${encodeURIComponent(member.name)}`} className={styles.secondaryButton}><Pencil size={15}/> Edit profile</Link><Link href="/members" className={styles.secondaryButton}><ArrowLeft size={15}/> Members</Link></div></div></div></div></section><InnerCta label="People of Ku-Ila" title={<>Meet the people<br />who make us <em>stronger.</em></>} description="Every member brings a distinct voice to the work of community." primaryHref="/members" primaryLabel="Meet every member" /></main>;}
