"use client";

import { FormEvent, useRef, useState } from "react";
import { Check, LoaderCircle, Send } from "lucide-react";
import TurnstileField from "./TurnstileField";
import { submitContactForm } from "@/lib/contactForm";

export default function ContactForm() {
  const [loading, setLoading] = useState(false); const [token, setToken] = useState(""); const [status, setStatus] = useState(""); const [success, setSuccess] = useState(false); const formRef = useRef<HTMLFormElement>(null);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { form.reportValidity(); return; } setLoading(true); setStatus(""); const data = new FormData(form); const result = await submitContactForm({ formType:"contact", subject:"New Contact Message — Ku-ila Website", name:String(data.get("name")), email:String(data.get("email")), message:String(data.get("message")), turnstileToken:token, fields:{ phone:String(data.get("phone") || ""), inquirySubject:String(data.get("inquiry_subject") || "") } }); setLoading(false); if(result.ok) { setSuccess(true); form.reset(); } else setStatus(result.message); }
  if (success) return <div className="rounded-[18px] bg-[#f7f5f0] p-8 text-center" role="status" tabIndex={-1}><Check className="mx-auto mb-3 text-[#f15a24]"/><h3 className="font-[family-name:var(--font-heading)] text-2xl text-[#0a1d4a]">Message received</h3><p className="mt-2 text-sm leading-relaxed text-[#0a1d4a]/65">Thank you. Your request has been received successfully.</p></div>;
  return <form ref={formRef} onSubmit={handleSubmit} className="space-y-6" noValidate><div className="grid grid-cols-1 gap-6 md:grid-cols-2"><Field label="Your Name" required><input name="name" required minLength={2} className="input-luxury" placeholder="Your full name" /></Field><Field label="Your Email" required><input name="email" type="email" required className="input-luxury" placeholder="your@email.com" /></Field></div><div className="grid grid-cols-1 gap-6 md:grid-cols-2"><Field label="Phone number"><input name="phone" type="tel" pattern="[+0-9() .-]{7,}" className="input-luxury" placeholder="+63 912 345 6789" /></Field><Field label="Subject"><input name="inquiry_subject" maxLength={120} className="input-luxury" placeholder="How can we help?" /></Field></div><Field label="Message" required><textarea name="message" required minLength={10} maxLength={4000} rows={5} className="input-luxury resize-none" placeholder="Write your message here..." /></Field><div className="sr-only" aria-hidden="true"><label>Leave this blank<input name="_honeypot" tabIndex={-1} autoComplete="off" /></label></div><TurnstileField onToken={setToken}/>{status ? <p role="alert" className="text-sm text-red-700">{status}</p> : null}<button type="submit" disabled={loading || (Boolean(process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY) && !token)} className="btn-theme btn-theme-primary disabled:opacity-50">{loading ? <><LoaderCircle className="w-4 h-4 animate-spin"/>Submitting…</> : <>Send Message<Send className="w-4 h-4"/></>}</button></form>;
}
function Field({label,required,children}:{label:string;required?:boolean;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-medium uppercase tracking-wider text-[#0a1d4a]">{label}{required?" *":""}</span>{children}</label>}
