"use client";

import { FormEvent, useState } from "react";
import { Check, LoaderCircle, Send } from "lucide-react";
import TurnstileField from "./TurnstileField";
import { submitContactForm } from "@/lib/contactForm";
import { trackFormSubmission } from "@/lib/gtag";

export default function MemberCenterRequestForm() {
  const [token, setToken] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { form.reportValidity(); return; } const data = new FormData(form); setLoading(true); setError(""); const result = await submitContactForm({ formType: "member-center-request", subject: `Member Center Request - ${String(data.get("request_type"))}`, name: String(data.get("name")), email: String(data.get("email")), message: String(data.get("message")), turnstileToken: token, fields: { requestType: String(data.get("request_type")), phone: String(data.get("phone") || ""), preferredContact: String(data.get("preferred_contact") || "") } }); setLoading(false); if (result.ok) { trackFormSubmission("member-center-request"); setSuccess(true); form.reset(); } else setError(result.message); };
  if (success) return <div className="rounded-2xl bg-[#f7f5f0] p-8 text-center" role="status"><Check className="mx-auto mb-3 text-[#f15a24]" /><h3 className="font-[family-name:var(--font-heading)] text-2xl text-[#0a1d4a]">Request received</h3><p className="mt-2 text-sm leading-relaxed text-[#0a1d4a]/65">A Ku-Ila officer will review your request and contact you when appropriate.</p></div>;
  return <form onSubmit={submit} className="rounded-2xl border border-[#0a1d4a]/10 bg-white p-6 shadow-[0_16px_36px_rgba(0,0,0,.06)] sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Your name" required><input className="input-luxury" name="name" required placeholder="Your full name" /></Field><Field label="Email" required><input className="input-luxury" name="email" type="email" required placeholder="name@example.com" /></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Request type" required><select className="input-luxury" name="request_type" required defaultValue=""><option value="" disabled>Choose an option</option><option>Event interest or RSVP</option><option>Volunteer or opportunity interest</option><option>Confidential feedback or concern</option><option>Community support request</option></select></Field><Field label="Phone number"><input className="input-luxury" name="phone" type="tel" placeholder="+63 912 345 6789" /></Field></div><Field label="Preferred way to be contacted"><select className="input-luxury" name="preferred_contact" defaultValue="Email"><option>Email</option><option>Phone</option><option>Facebook Messenger</option></select></Field><Field label="Tell us more" required><textarea className="input-luxury min-h-36 resize-y" name="message" required minLength={10} placeholder="Share the event, opportunity, feedback, or support you are asking about." /></Field><TurnstileField onToken={setToken} />{error ? <p role="alert" className="mt-4 text-sm text-red-700">{error}</p> : null}<button type="submit" disabled={loading || (Boolean(process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY) && !token)} className="btn-theme btn-theme-primary mt-6 disabled:opacity-50">{loading ? <><LoaderCircle className="h-4 w-4 animate-spin" /> Sending...</> : <>Send Request <Send className="h-4 w-4" /></>}</button></form>;
}

function Field({ label, children, required = false }: { label: string; children: React.ReactNode; required?: boolean }) { return <label className="block"><span className="mb-2 block text-sm font-medium uppercase tracking-wider text-[#0a1d4a]">{label}{required ? " *" : ""}</span>{children}</label>; }
