"use client";

import { FormEvent, useEffect, useId, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronLeft, ChevronRight, LoaderCircle, Pencil, X } from "lucide-react";
import styles from "./ProfileUpdateRequestModal.module.css";
import TurnstileField from "./TurnstileField";
import { submitContactForm } from "@/lib/contactForm";
import { trackFormSubmission } from "@/lib/gtag";

type MemberIdentity = { name: string; slug: string; role: string; pageUrl: string };
const steps = ["Basic Information", "Identity and Pronouns", "Organization Role", "Work and Skills", "Biography and Contributions", "Photo and Files", "Contact and Social Links", "Review and Submit"];
const orientations = ["Gay", "Lesbian", "Bisexual", "Pansexual", "Asexual", "Demisexual", "Queer", "Questioning", "Heterosexual / Straight", "Prefer Not to Say", "Self-Describe"];
const identities = ["Woman", "Man", "Transgender Woman", "Transgender Man", "Nonbinary", "Genderfluid", "Genderqueer", "Agender", "Bigender", "Intersex", "Two-Spirit", "Questioning", "Prefer Not to Say", "Self-Describe"];

function Field({ label, help, children, required = false }: { label: string; help?: string; children: React.ReactNode; required?: boolean }) { return <label className={styles.field}><span>{label}{required ? <b aria-hidden="true"> *</b> : null}</span>{children}{help ? <small>{help}</small> : null}</label>; }
function Checks({ name, options, onChange }: { name: string; options: string[]; onChange?: () => void }) { return <div className={styles.checks}>{options.map(option => <label key={option}><input type="checkbox" name={name} value={option} onChange={onChange} /> <span>{option}</span></label>)}</div>; }

export default function ProfileUpdateRequestModal({ member }: { member: MemberIdentity }) {
  const [open, setOpen] = useState(false); const [step, setStep] = useState(0); const [nameChange, setNameChange] = useState(false); const [otherPronouns, setOtherPronouns] = useState(false); const [orientationOther, setOrientationOther] = useState(false); const [identityOther, setIdentityOther] = useState(false); const [turnstileToken, setTurnstileToken] = useState(""); const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState("");
  const opener = useRef<HTMLButtonElement>(null); const dialog = useRef<HTMLDivElement>(null); const titleId = useId();
  const close = () => { setOpen(false); setError(""); setTimeout(() => opener.current?.focus(), 0); };
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (event.key !== "Tab" || !dialog.current) return; const focusable = dialog.current.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [href]'); const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }; document.addEventListener("keydown", onKey); const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; setTimeout(() => dialog.current?.querySelector<HTMLElement>("button")?.focus(), 0); return () => { document.removeEventListener("keydown", onKey); document.body.style.overflow = previous; }; }, [open]);
  const next = () => { const active = dialog.current?.querySelector<HTMLElement>(".step-active"); const invalid = active?.querySelector<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>("[required]:invalid"); if (invalid) { invalid.focus(); invalid.reportValidity(); return; } setStep(current => Math.min(current + 1, steps.length - 1)); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { form.reportValidity(); return; } const data = new FormData(form); const photo = data.get("profile_photo"); const attachments = data.getAll("supporting_files").filter((file): file is File => file instanceof File && file.size > 0); const allFiles = [photo, ...attachments].filter((file): file is File => file instanceof File && file.size > 0); if (photo instanceof File && photo.size > 0 && !data.get("photo_permission")) { setError("Please confirm that you own the new profile photo or have permission to submit it."); return; } if ((photo instanceof File && photo.size > 5 * 1024 * 1024) || attachments.some(file => file.size > (file.type === "application/pdf" ? 10 : 5) * 1024 * 1024) || attachments.length > 3) { setError("Images must be 5 MB or smaller, PDFs 10 MB or smaller, with a maximum of three supporting files."); return; } const recent = Number(localStorage.getItem(`profile-request-${member.slug}`) || 0); if (Date.now() - recent < 60_000) { setError("A request for this profile was just sent. Please wait a minute before sending another."); return; } setLoading(true); setError(""); const fields: Record<string, string> = {}; data.forEach((value, key) => { if (typeof value !== "string" || key === "contact_email" || key === "requested_changes_summary" || key === "_honeypot") return; fields[key] = fields[key] ? `${fields[key]}\n${value}` : value; }); const result = await submitContactForm({ formType:"profile-update-request", subject:`Profile Update Request — ${member.name}`, name:String(data.get("full_name")), email:String(data.get("contact_email")), message:String(data.get("requested_changes_summary")), turnstileToken, fields:{ ...fields, memberName:member.name, memberId:member.slug, profileUrl:window.location.href }, files:allFiles }); setLoading(false); if (result.ok) { trackFormSubmission("profile-update-request"); localStorage.setItem(`profile-request-${member.slug}`, String(Date.now())); setSuccess(true); } else setError(result.message); };
  const modal = open && typeof document !== "undefined" ? createPortal(<div className={styles.overlay} role="presentation"><div ref={dialog} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby={titleId}>
    <header className={styles.header}><div><p>Profile being updated</p><h2 id={titleId}>Request a Profile Update</h2><span>{member.name}</span></div><button type="button" onClick={close} aria-label="Close profile update request"><X /></button></header>
    {success ? <div className={styles.success}><Check size={34} /><h3>Thank you.</h3><p>Your profile update request has been received and will be reviewed before any changes are published.</p><button type="button" className={styles.submit} onClick={close}>Close</button></div> : <form onSubmit={submit} className={styles.form} encType="multipart/form-data">
      <input type="hidden" name="member_name" value={member.name} /><input type="hidden" name="member_id" value={member.slug} /><input type="hidden" name="profile_url" value={member.pageUrl} /><div className={styles.honeypot}><input name="_honeypot" tabIndex={-1} autoComplete="off" /></div>
      <div className={styles.progress}><span>Step {step + 1} of {steps.length}</span><strong>{steps[step]}</strong><div><i style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div></div>
      <div className={`${styles.step} ${step === 0 ? "step-active" : ""}`} hidden={step !== 0}><p className={styles.intro}>Submit the information you would like us to add or change. Your request will be reviewed before any updates appear on your public profile.</p><div className={styles.grid}><Field label="Full Name" required help="Enter your complete name as you would like it to appear publicly."><input name="full_name" defaultValue={member.name} required placeholder="Ricson M. Cultura" /></Field><Field label="Contact Email" required help="Used only to reply about this request; it is not shown publicly."><input name="contact_email" type="email" required placeholder="name@example.com" /></Field><Field label="Nickname / Also Known As" help="Enter the nickname or name people commonly use for you."><input name="nickname" placeholder="Rics" /></Field></div><Field label="Would you like to request a name change?"><select name="name_change" onChange={e => setNameChange(e.target.value === "Yes")}><option>No</option><option>Yes</option></select></Field>{nameChange ? <><Field label="Requested Display Name"><input name="requested_display_name" placeholder="Ricson Cultura" /></Field><Field label="Reason for the requested name change"><textarea name="name_change_reason" placeholder="I would like my middle initial removed from the public profile." /></Field></> : null}</div>
      <div className={`${styles.step} ${step === 1 ? "step-active" : ""}`} hidden={step !== 1}><Field label="Pronouns" help="Optional. Only approved information will appear publicly."><select name="pronouns" onChange={e => setOtherPronouns(e.target.value === "Other")}><option value="">Choose an option</option>{["He/Him", "She/Her", "They/Them", "He/They", "She/They", "Any Pronouns", "Prefer Not to Say", "Other"].map(item => <option key={item}>{item}</option>)}</select></Field>{otherPronouns ? <Field label="Other Pronouns"><input name="other_pronouns" placeholder="They/She" /></Field> : null}<Field label="Sexual Orientation" help="Optional. Select any options that describe you; leave blank if you do not want it shown publicly."><Checks name="orientation" options={orientations} onChange={() => setOrientationOther([...document.querySelectorAll<HTMLInputElement>('input[name="orientation"]')].some(input => input.checked && input.value === "Self-Describe"))} />{orientationOther ? <input name="orientation_self_describe" placeholder="Self-describe" /> : null}</Field><Field label="Gender Identity" help="Optional. Only approved information should appear publicly."><Checks name="identity" options={identities} onChange={() => setIdentityOther([...document.querySelectorAll<HTMLInputElement>('input[name="identity"]')].some(input => input.checked && input.value === "Self-Describe"))} />{identityOther ? <input name="identity_self_describe" placeholder="Self-describe" /> : null}</Field><Field label="How would you like your identity or community affiliation described?" help="Use the wording you are comfortable displaying publicly."><textarea name="identity_description" placeholder="LGBTQIA++ advocate and community organizer" /></Field></div>
      <div className={`${styles.step} ${step === 2 ? "step-active" : ""}`} hidden={step !== 2}><Field label="Current Role in the Organization"><input name="current_role" defaultValue={member.role} placeholder="LGBTQIA++ Kumintang Ilaya President" /></Field><Field label="Previous Roles" help="Enter one role per line."><textarea name="previous_roles" placeholder={"Board Member\nEvents Committee Coordinator"} /></Field><div className={styles.grid}><Field label="Organization / Chapter"><input name="chapter" placeholder="LGBTQIA++ SILBI Kumintang Ilaya" /></Field><Field label="Year Joined"><input name="year_joined" inputMode="numeric" pattern="[0-9]{4}" placeholder="2022" /></Field></div><Field label="Committees and Areas of Involvement" help="Enter one entry per line."><textarea name="committees" placeholder={"Community Outreach\nMembership\nEvents"} /></Field></div>
      <div className={`${styles.step} ${step === 3 ? "step-active" : ""}`} hidden={step !== 3}><Field label="Currently Working As" help="Enter one occupation or profession per line."><textarea name="work" placeholder={"Makeup Artist\nFashion Designer"} /></Field><Field label="Skills and Talents" help="Enter one skill per line."><textarea name="skills" placeholder={"Hair and Makeup\nEvent Production\nPublic Speaking"} /></Field><div className={styles.grid}><Field label="Business, Brand, or Professional Name"><input name="business_name" placeholder="Ricson Cultura Makeup Artistry" /></Field><Field label="Website or Business Page"><input name="business_url" type="url" placeholder="https://example.com" /></Field></div></div>
      <div className={`${styles.step} ${step === 4 ? "step-active" : ""}`} hidden={step !== 4}><Field label="Short Biography" help="Write two to four sentences about yourself."><textarea name="biography" rows={5} placeholder="Ricson is a community leader, makeup artist, and advocate..." /></Field><Field label="Your Story" help="This may be edited for clarity before it appears publicly."><textarea name="story" rows={6} placeholder="Share a short story about your journey and the people who inspired you." /></Field><Field label="Advocacy Interests" help="Enter one topic per line."><textarea name="advocacy" placeholder={"Equal rights\nMental health awareness\nYouth empowerment"} /></Field><Field label="Community Contributions" help="Enter one contribution per line."><textarea name="contributions" placeholder={"Organized local Pride activities\nSupported membership outreach"} /></Field><Field label="Achievements and Awards" help="Enter one achievement per line and include the year when available."><textarea name="achievements" placeholder={"Champion — Commercial Makeup Competition, 2026\nVolunteer Recognition Award, 2025"} /></Field><Field label="Favorite Quote or Personal Message"><textarea name="quote" placeholder="Be proud of who you are and help others feel safe doing the same." /></Field></div>
      <div className={`${styles.step} ${step === 5 ? "step-active" : ""}`} hidden={step !== 5}><Field label="Upload New Profile Photo" help="JPG, JPEG, PNG, or WebP. Upload a clear portrait; it may be cropped to match the member directory style."><input name="profile_photo" type="file" accept="image/jpeg,image/png,image/webp" /></Field><label className={styles.agree}><input name="photo_permission" type="checkbox" /> I confirm that I own this image or have permission to submit it for use on this website.</label><Field label="Photo credit or photographer name"><input name="photo_credit" placeholder="Juan Dela Cruz Photography" /></Field><Field label="Supporting Files" help="Optional: PDF, JPG, PNG, or WebP—such as certificates, appointment letters, or reference images. Files are never published automatically."><input name="supporting_files" type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" /></Field></div>
      <div className={`${styles.step} ${step === 6 ? "step-active" : ""}`} hidden={step !== 6}><div className={styles.grid}><Field label="Public Email Address"><input name="public_email" type="email" placeholder="name@example.com" /></Field><Field label="Contact Number"><input name="public_phone" type="tel" placeholder="+63 912 345 6789" /></Field></div><label className={styles.agree}><input name="email_permission" type="checkbox" /> I give permission for this email address to appear publicly.</label><label className={styles.agree}><input name="phone_permission" type="checkbox" /> I give permission for this phone number to appear publicly.</label><div className={styles.grid}>{["Facebook", "Instagram", "TikTok", "YouTube", "LinkedIn", "Other public profile"].map(network => <Field key={network} label={network}><input name={network.toLowerCase().replaceAll(" ", "_")} type="url" placeholder={`https://${network.toLowerCase().replaceAll(" ", "")}.com/username`} /></Field>)}</div></div>
      <div className={`${styles.step} ${step === 7 ? "step-active" : ""}`} hidden={step !== 7}><Field label="Please summarize the changes you are requesting" required><textarea name="requested_changes_summary" required rows={6} placeholder="Please update my current role, add my makeup artist profession, replace my profile photo, and add my Instagram link." /></Field><div className={styles.review}><p>Your request is linked to <strong>{member.name}</strong> and will be reviewed before anything is published.</p><label className={styles.agree}><input name="accurate" type="checkbox" required /> I confirm that the information I submitted is accurate.</label><label className={styles.agree}><input name="review_understood" type="checkbox" required /> I understand that this request will be reviewed before it appears on the website.</label><label className={styles.agree}><input name="public_permission" type="checkbox" required /> I give permission for the approved information to appear on my public member profile.</label></div><TurnstileField onToken={setTurnstileToken} /></div>
      {error ? <p className={styles.error} role="alert">{error}</p> : null}<footer className={styles.footer}>{step > 0 ? <button type="button" className={styles.back} onClick={() => setStep(current => current - 1)}><ChevronLeft size={16}/> Back</button> : <span />}{step < steps.length - 1 ? <button type="button" className={styles.submit} onClick={next}>Continue <ChevronRight size={16}/></button> : <button className={styles.submit} disabled={loading || (Boolean(process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY) && !turnstileToken)}>{loading ? <LoaderCircle className={styles.spin} size={16}/> : null} Submit Profile Update Request</button>}</footer>
    </form>}</div></div>, document.body) : null;
  return <><button ref={opener} type="button" className={styles.requestButton} onClick={() => { setSuccess(false); setStep(0); setOpen(true); }}><Pencil size={15} /> Request Profile Edit</button>{modal}</>;
}
