"use client";

import { FormEvent, useCallback, useEffect, useId, useRef, useState } from "react";
import { Check, HeartHandshake, LoaderCircle, X } from "lucide-react";
import { createPortal } from "react-dom";
import TurnstileField from "./TurnstileField";
import { submitContactForm } from "@/lib/contactForm";
import styles from "./SponsorshipInquiryForm.module.css";

const supportOptions = ["Financial sponsorship", "Event supplies", "Venue support", "Food or refreshments", "Printing", "Event shirts", "Transportation", "Photography or media", "Professional services", "Volunteer support", "Other"];

export default function SponsorshipInquiryForm() {
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState(""); const [token, setToken] = useState("");
  const opener = useRef<HTMLButtonElement>(null); const dialog = useRef<HTMLDivElement>(null); const titleId = useId();
  const close = useCallback(() => { if (loading) return; setOpen(false); setError(""); setTimeout(() => opener.current?.focus(), 0); }, [loading]);
  useEffect(() => { if (!open) return; const previous = document.body.style.overflow; const keyboard = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; document.body.style.overflow = "hidden"; document.addEventListener("keydown", keyboard); return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", keyboard); }; }, [open, close]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { form.reportValidity(); return; } const data = new FormData(form); setLoading(true); setError(""); const supportTypes = data.getAll("support_type").map(String); const result = await submitContactForm({ formType: "sponsorship-inquiry", subject: "New Pride Partnership Inquiry — Ku-ila Website", name: String(data.get("full_name")), email: String(data.get("email")), message: String(data.get("message")), turnstileToken: token, fields: { organization: String(data.get("organization") || ""), phone: String(data.get("phone") || ""), supportTypes, eventInterest: String(data.get("event_interest") || ""), sponsorshipRange: String(data.get("sponsorship_range") || ""), inKindDetails: String(data.get("in_kind_details") || ""), consent: Boolean(data.get("consent")) } }); setLoading(false); if (result.ok) setSuccess(true); else setError(result.message); };
  const modal = open && typeof document !== "undefined" ? createPortal(<div className={styles.overlay} role="presentation"><div className={styles.dialog} ref={dialog} role="dialog" aria-modal="true" aria-labelledby={titleId}>
    <header><div><p>Stand with Pride</p><h2 id={titleId}>Become a Pride Partner</h2></div><button type="button" aria-label="Close partnership inquiry" onClick={close}><X size={20}/></button></header>
    {success ? <div className={styles.success} role="status" tabIndex={-1}><Check size={34}/><h3>Thank you.</h3><p>Your Pride Partnership inquiry has been received. We will be in touch soon.</p><button type="button" className={styles.submit} onClick={close}>Close</button></div> : <form onSubmit={submit} noValidate><p className={styles.intro}>Tell us how you would like to help future community programs and Pride celebrations.</p><div className={styles.grid}><label>Full Name *<input name="full_name" required placeholder="Your full name" /></label><label>Organization or Business Name<input name="organization" placeholder="Optional" /></label><label>Email *<input name="email" type="email" required placeholder="name@example.com" /></label><label>Contact Number<input name="phone" type="tel" placeholder="+63 912 345 6789" /></label></div><label>Type of Support<div className={styles.checks}>{supportOptions.map(option => <label key={option}><input type="checkbox" name="support_type" value={option} />{option}</label>)}</div></label><div className={styles.grid}><label>Event or Program of Interest<input name="event_interest" placeholder="Pride March or another program" /></label><label>Estimated Sponsorship Range <span>Optional</span><select name="sponsorship_range"><option value="">Prefer not to say</option><option>Below ₱5,000</option><option>₱5,000–₱10,000</option><option>₱10,000–₱25,000</option><option>Above ₱25,000</option></select></label></div><label>In-kind Support Details<textarea name="in_kind_details" placeholder="Tell us about supplies, services, or other support you can provide." /></label><label>Message *<textarea name="message" required minLength={10} placeholder="How would you like to partner with Ku-Ila?" /></label><label className={styles.consent}><input type="checkbox" name="consent" required />I agree that Ku-Ila may contact me about this partnership inquiry.</label><TurnstileField onToken={setToken}/>{error ? <p className={styles.error} role="alert">{error}</p> : null}<button className={styles.submit} disabled={loading || (Boolean(process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY) && !token)}>{loading ? <><LoaderCircle size={16} className={styles.spin}/>Submitting…</> : "Send Partnership Inquiry"}</button></form>}
  </div></div>, document.body) : null;
  return <><button className={styles.trigger} type="button" ref={opener} onClick={() => { setSuccess(false); setOpen(true); }}><HeartHandshake size={17}/> Become a Pride Partner</button>{modal}</>;
}
