import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Bell, CalendarDays, CircleUserRound, HeartHandshake, Megaphone, Users, Wrench } from "lucide-react";
import HeroSection from "@/components/HeroSection";
import InnerCta from "@/components/InnerCta";
import MemberCenterRequestForm from "@/components/MemberCenterRequestForm";
import styles from "@/components/InnerPage.module.css";
import { communityResources } from "@/lib/data";
import { pageSeo } from "@/lib/seo";

export const metadata: Metadata = pageSeo({ title: "Ku-Ila Member Center", description: "Events, community resources, opportunities, announcements, and support tools for LGBTQIA++ Kumintang Ilaya members.", path: "/member-center", image: "/images/stock/stock-04.jpg" });

const tools = [
  { icon: CircleUserRound, title: "My profile", text: "Request updates to your public member profile.", href: "/members" },
  { icon: CalendarDays, title: "Events hub", text: "Register interest for upcoming gatherings and receive updates.", href: "#request" },
  { icon: Users, title: "Member directory", text: "Meet the people and skills that make up Ku-Ila.", href: "/members" },
  { icon: HeartHandshake, title: "Support request", text: "Ask for confidential community support or guidance.", href: "#request" },
];
const announcements = ["Membership applications are reviewed after payment verification.", "Upcoming event and volunteer updates will be shared through the Member Center.", "Members can submit profile edits, opportunities, concerns, and support requests below."];
const opportunities = ["Volunteer at community events and outreach activities.", "Share a skill, workshop idea, or service for fellow members.", "Join planning conversations for future Ku-Ila programs."];

export default function MemberCenterPage() { return <main><HeroSection title="Member Center" subtitle="Home / Member Center" description="A practical place for Ku-Ila members to stay informed, get involved, and ask for support." backgroundImage="/images/stock/stock-04.jpg" />
  <section className={`${styles.section} ${styles.cream}`}><div className={styles.wrap}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Member tools</p><h2 className={styles.heading}>Stay connected,<br /><em>stay involved.</em></h2></div><p className={styles.lead}>Use these services to manage your public profile, discover community opportunities, and reach the Ku-Ila team.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tools.map(({ icon: Icon, title, text, href }) => <Link key={title} href={href} className="rounded-2xl border border-[#0a1d4a]/10 bg-white p-6 transition hover:-translate-y-1 hover:border-[#f15a24]/50"><Icon className="mb-5 h-6 w-6 text-[#f15a24]" /><h3 className="font-[family-name:var(--font-heading)] text-2xl text-[#0a1d4a]">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#0a1d4a]/65">{text}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#f15a24]">Open <ArrowRight size={15} /></span></Link>)}</div></div></section>
  <section className={styles.section}><div className={styles.wrap}><div className="grid gap-12 lg:grid-cols-2"><div><p className={styles.eyebrow}>Announcements</p><h2 className={styles.heading}>What members<br /><em>need to know.</em></h2><div className="mt-8 space-y-4">{announcements.map((announcement, index) => <article key={announcement} className="flex gap-4 rounded-2xl border border-[#0a1d4a]/10 p-5"><Bell className="mt-1 h-5 w-5 shrink-0 text-[#f15a24]" /><div><span className="text-xs font-bold uppercase tracking-wider text-[#f15a24]">Update 0{index + 1}</span><p className="mt-2 text-sm leading-relaxed text-[#0a1d4a]/70">{announcement}</p></div></article>)}</div></div><div><p className={styles.eyebrow}>Opportunities</p><h2 className={styles.heading}>Bring what you<br /><em>care about.</em></h2><div className="mt-8 space-y-4">{opportunities.map(opportunity => <article key={opportunity} className="flex gap-4 rounded-2xl bg-[#f7f5f0] p-5"><Wrench className="mt-1 h-5 w-5 shrink-0 text-[#f15a24]" /><p className="text-sm leading-relaxed text-[#0a1d4a]/70">{opportunity}</p></article>)}<a href="#request" className="inline-flex items-center gap-2 text-sm font-semibold text-[#f15a24]">Express interest <ArrowRight size={15} /></a></div></div></div></div></section>
  <section className={`${styles.section} ${styles.cream}`}><div className={styles.wrap}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Resources</p><h2 className={styles.heading}>Knowledge that helps<br /><em>our community thrive.</em></h2></div><p className={styles.lead}>Curated external resources on safety, wellbeing, equality, and inclusive learning.</p></div><div className="grid gap-5 md:grid-cols-2">{communityResources.map(resource => <a key={resource.url} href={resource.url} target="_blank" rel="noreferrer" className="rounded-2xl border border-[#0a1d4a]/10 bg-white p-6 transition hover:border-[#f15a24]/50"><span className="text-xs font-bold uppercase tracking-wider text-[#f15a24]">{resource.source}</span><h3 className="mt-3 font-[family-name:var(--font-heading)] text-2xl leading-tight text-[#0a1d4a]">{resource.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#0a1d4a]/65">{resource.description}</p></a>)}</div></div></section>
  <section id="request" className={styles.section}><div className={styles.wrap}><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className={styles.eyebrow}>Get in touch</p><h2 className={styles.heading}>Ask, share, or<br /><em>get support.</em></h2><p className={styles.lead}>Use this form for event interest, opportunities, confidential feedback, and community support requests. It is reviewed by the Ku-Ila team.</p><Megaphone className="mt-8 h-10 w-10 text-[#f15a24]" /></div><MemberCenterRequestForm /></div></div></section>
  <InnerCta label="Your community" title={<>There is always<br />room to <em>belong.</em></>} description="Keep building connection by joining an event, sharing your skills, or reaching out when you need support." primaryHref="/events" primaryLabel="Explore events" secondaryHref="/members" secondaryLabel="Meet members" />
</main>; }
