import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bell, CalendarDays, CircleUserRound, HeartHandshake, Megaphone, Users, Wrench } from "lucide-react";
import HeroSection from "@/components/HeroSection";
import InnerCta from "@/components/InnerCta";
import MemberCenterRequestForm from "@/components/MemberCenterRequestForm";
import styles from "@/components/InnerPage.module.css";
import { communityResources } from "@/lib/data";
import { pageSeo } from "@/lib/seo";

export const metadata: Metadata = pageSeo({ title: "Ku-Ila Member Center", description: "Events, community resources, opportunities, announcements, and support tools for LGBTQIA++ Kumintang Ilaya members.", path: "/member-center", image: "/images/stock/stock-04.jpg" });
const tools = [{ icon: CircleUserRound, title: "My profile", description: "Request updates to your public member profile.", href: "/members" }, { icon: CalendarDays, title: "Events hub", description: "Register interest for upcoming gatherings.", href: "#request" }, { icon: Users, title: "Member directory", description: "Meet the people and skills in Ku-Ila.", href: "/members" }, { icon: HeartHandshake, title: "Support request", description: "Ask for confidential community guidance.", href: "#request" }];
const announcements = ["Membership applications are reviewed after payment verification.", "Upcoming event and volunteer updates will be shared here.", "Profile edits, opportunities, concerns, and support requests can be sent below."];

export default function MemberCenterPage() { return <main><HeroSection title="Member Center" subtitle="Home / Member Center" description="A practical place for Ku-Ila members to stay informed, get involved, and ask for support." backgroundImage="/images/stock/stock-04.jpg" />
  <section className={styles.section}><div className={styles.wrap}><div className={styles.intro}><div className={styles.copy}><p className={styles.eyebrow}>For members</p><h2 className={styles.heading}>A place to stay<br /><em>connected.</em></h2><p>Use the Member Center to find community resources, express interest in future events, share what you can offer, and reach the Ku-Ila team when you need support.</p><p>Everything here is designed to make participation easier and keep the community close.</p><div className={styles.featureList}><div className={styles.feature}><span className={styles.featureIcon}><Bell size={18}/></span><div><b>Stay informed</b>Receive updates about membership, activities, and opportunities to get involved.</div></div><div className={styles.feature}><span className={styles.featureIcon}><HeartHandshake size={18}/></span><div><b>Reach out safely</b>Send a confidential request for guidance, feedback, or community support.</div></div></div><div className={styles.actions}><a href="#request" className={styles.primaryButton}>Send a request <ArrowRight size={16}/></a></div></div><div className={styles.visual}><div className={styles.primaryVisual}><Image src="/images/stock/stock-03.jpg" alt="Ku-Ila community members together" fill sizes="(max-width:820px) 82vw, 520px" /></div><div className={styles.secondaryVisual}><Image src="/images/logo/731350583_10238772116515608_5057049016834242279_n.jpg" alt="Ku-Ila logo" fill sizes="235px" /></div></div></div></div></section>
  <section className={`${styles.section} ${styles.cream}`}><div className={styles.wrap}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Member tools</p><h2 className={styles.heading}>Support that meets<br /><em>our community where it is.</em></h2></div><p className={styles.lead}>Choose the member service that fits what you need today.</p></div><div className={styles.programRows}>{tools.map(({ icon: Icon, title, description, href }, index) => <Link className={styles.programRow} href={href} key={title}><span className={styles.rowNumber}>0{index + 1}</span><Icon className={styles.rowIcon} size={22}/><h3>{title}</h3><p>{description}</p><span className={styles.rowArrow}><ArrowRight size={17}/></span></Link>)}</div></div></section>
  <section className={styles.section}><div className={styles.wrap}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Announcements</p><h2 className={styles.heading}>What members<br /><em>need to know.</em></h2></div><p className={styles.lead}>A short view of the latest community information and opportunities.</p></div><div className={styles.cards}>{announcements.map((announcement, index) => <article key={announcement} className={styles.imageCard}><div className="rounded-[18px] bg-[#0a1d4a] p-7 text-white"><span className="text-xs font-bold uppercase tracking-wider text-[#f4a137]">Update 0{index + 1}</span><Megaphone className="my-7 h-9 w-9 text-[#f15a24]"/><p className="!text-white/85 text-base leading-relaxed">{announcement}</p></div></article>)}</div></div></section>
  <section className={`${styles.section} ${styles.cream}`}><div className={styles.wrap}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Resources and opportunities</p><h2 className={styles.heading}>Bring what you<br /><em>care about.</em></h2></div><p className={styles.lead}>Explore useful knowledge, volunteer opportunities, and ways to share your skills with the community.</p></div><div className="grid gap-5 md:grid-cols-2">{communityResources.map(resource => <a key={resource.url} href={resource.url} target="_blank" rel="noreferrer" className="rounded-[18px] border border-[#0a1d4a]/10 bg-white p-7 transition hover:border-[#f15a24]/60"><span className="text-xs font-bold uppercase tracking-wider text-[#f15a24]">{resource.source}</span><h3 className="mt-4 font-[family-name:var(--font-heading)] text-2xl leading-tight text-[#0a1d4a]">{resource.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#0a1d4a]/65">{resource.description}</p></a>)}<a href="#request" className="rounded-[18px] bg-[#f15a24] p-7 text-white"><Wrench className="h-8 w-8"/><h3 className="mt-6 font-[family-name:var(--font-heading)] text-3xl">Share your skills.</h3><p className="mt-3 text-sm leading-relaxed text-white/80">Volunteer, propose a workshop, or offer a service that could benefit fellow members.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">Express interest <ArrowRight size={15}/></span></a></div></div></section>
  <section id="request" className={styles.section}><div className={styles.wrap}><div className={styles.formLayout}><div><p className={styles.eyebrow}>Get in touch</p><h2 className={styles.heading}>Ask, share, or<br /><em>get support.</em></h2><p className={styles.lead}>Use this form for event interest, opportunities, confidential feedback, and community support requests. The Ku-Ila team reviews every request.</p></div><MemberCenterRequestForm /></div></div></section>
  <InnerCta label="Your community" title={<>There is always<br />room to <em>belong.</em></>} description="Keep building connection by joining an event, sharing your skills, or reaching out when you need support." primaryHref="/events" primaryLabel="Explore events" secondaryHref="/members" secondaryLabel="Meet members" /></main>; }
