import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CalendarDays, CircleUserRound, HeartHandshake, Megaphone, Users, Wrench } from "lucide-react";
import InnerCta from "@/components/InnerCta";
import MemberCenterRequestForm from "@/components/MemberCenterRequestForm";
import { communityResources } from "@/lib/data";
import { pageSeo } from "@/lib/seo";
import styles from "./member-center.module.css";

export const metadata: Metadata = pageSeo({ title: "Ku-Ila Member Center", description: "Events, community resources, opportunities, announcements, and support tools for LGBTQIA++ Kumintang Ilaya members.", path: "/member-center", image: "/images/stock/stock-04.jpg" });
const tools = [{ icon: CircleUserRound, title: "My profile", text: "Request changes to your public member profile.", href: "/members" }, { icon: CalendarDays, title: "Events hub", text: "Register interest for future gatherings.", href: "#request" }, { icon: Users, title: "Directory", text: "Meet the people and skills in Ku-Ila.", href: "/members" }, { icon: HeartHandshake, title: "Support", text: "Request confidential community guidance.", href: "#request" }];
const announcements = ["Membership applications are reviewed after payment verification.", "Upcoming event and volunteer updates will be shared here.", "Profile edits, opportunities, concerns, and support requests can be sent below."];
const opportunities = ["Volunteer at community events and outreach activities.", "Offer a skill, workshop idea, or service to fellow members.", "Help plan future Ku-Ila programs and gatherings."];

export default function MemberCenterPage() { return <main><section className={styles.hero}><div className={styles.wrap}><p className={styles.crumb}>Home / Member Center</p><div className={styles.heroGrid}><div><h1>For your<br /><em>community.</em></h1><p className={styles.heroCopy}>A home base for staying informed, sharing what you can offer, and reaching Ku-Ila when you need support.</p></div><aside className={styles.heroNote}><span>Member note</span><strong>Come as you are.</strong><p>This space is built to make participation, support, and connection easier to find.</p></aside></div></div></section>
<section className={`${styles.section} ${styles.cream}`}><div className={styles.wrap}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Start here</p><h2 className={styles.heading}>Four ways to<br /><em>stay connected.</em></h2></div><p className={styles.lead}>Open the tool that fits what you need today. Every route is designed to help members take a simple next step.</p></div><div className={styles.quickGrid}>{tools.map(({ icon: Icon, title, text, href }, index) => <Link key={title} href={href} className={styles.quick}><span className={styles.quickNum}>0{index + 1}</span><Icon size={25} /><h3>{title}</h3><p>{text}</p><span className={styles.quickAction}>Open <ArrowRight size={14} /></span></Link>)}</div></div></section>
<section className={styles.section}><div className={styles.wrap}><div className={styles.board}><div className={styles.updates}><p className={styles.eyebrow}>Announcements</p><h2 className={styles.heading}>The latest<br /><em>from Ku-Ila.</em></h2>{announcements.map((announcement, index) => <article className={styles.update} key={announcement}><span>0{index + 1}</span><p>{announcement}</p></article>)}</div><div className={styles.opportunities}><p className={styles.eyebrow}>Get involved</p><h2>Bring what you<br />care about.</h2>{opportunities.map(opportunity => <article className={styles.opportunity} key={opportunity}><Wrench size={18} /><span>{opportunity}</span></article>)}<a href="#request" className={styles.interest}>Express interest <ArrowRight size={15} /></a></div></div></div></section>
<section className={`${styles.section} ${styles.cream}`}><div className={styles.wrap}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Resources</p><h2 className={styles.heading}>Useful knowledge,<br /><em>when you need it.</em></h2></div><p className={styles.lead}>Trusted external reading on safety, wellbeing, equality, and inclusive learning.</p></div><div className={styles.resourceGrid}>{communityResources.map(resource => <a key={resource.url} href={resource.url} target="_blank" rel="noreferrer" className={styles.resource}><span>{resource.source}</span><h3>{resource.title}</h3><p>{resource.description}</p></a>)}</div></div></section>
<section id="request" className={styles.section}><div className={styles.wrap}><div className={styles.request}><div className={styles.requestCopy}><p className={styles.eyebrow}>One request form</p><h2 className={styles.heading}>Ask, share, or<br /><em>get support.</em></h2><p className={styles.lead}>Use this for event interest, opportunity ideas, confidential feedback, and community support. The Ku-Ila team reviews every request.</p><span className={styles.requestIcon}><Megaphone size={28} /></span></div><MemberCenterRequestForm /></div></div></section>
<InnerCta label="Your community" title={<>There is always<br />room to <em>belong.</em></>} description="Keep building connection by joining an event, sharing your skills, or reaching out when you need support." primaryHref="/events" primaryLabel="Explore events" secondaryHref="/members" secondaryLabel="Meet members" /></main>; }
